# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28c28a4d97ef36d447c1d4cad68a952db4f81c38dbf68185e663bfeca037feb0c1e5802787f4121a4389687b70ca96d919d0b2d85a100af08dc1d03e335617d5
  fb_api_id: 1686818004902834
  fb_api_secret: 606183a95835cf071c9d6c35ee1d93d5
  fb_callback_url: http://localhost:3000/shares/index
  twitter_api_id: xHalD4vv9wCztGk1imJN1a0tJ
  twitter_api_secret: 0A5Qu14U2sjgCiwtd7ijRdrH9gQEKRE16rDA7DbxxCP2RaJRlS
  gplus_api_id: 933760275996-8muh4su7nrlerjeca98ttfj5m6bf7ap5.apps.googleusercontent.com
  gplus_api_secret: FlviCSzz1m1fV_IaM0-6RjfF
  linkedin_api_id: 75remaypoe0ddp
  linkedin_api_secret: aRsYMhFYowHEEmFV

test:
  secret_key_base: 983ee86d9efc71d5846a08a3601dd6c6e1f62a84666f448ff621e2ffb0066f6f637cf18baf196f24cda7bcdbec539d8c3722732ff4f2c422798657a84be9c8e6
  fb_api_id: 1686818004902834
  fb_api_secret: 606183a95835cf071c9d6c35ee1d93d5
  fb_callback_url: "http://localhost:3000/users/auth/facebook/callback"
  twitter_api_id: xHalD4vv9wCztGk1imJN1a0tJ
  twitter_api_secret: 0A5Qu14U2sjgCiwtd7ijRdrH9gQEKRE16rDA7DbxxCP2RaJRlS
  gplus_api_id: 933760275996-8muh4su7nrlerjeca98ttfj5m6bf7ap5.apps.googleusercontent.com
  gplus_api_secret: FlviCSzz1m1fV_IaM0-6RjfF
  linkedin_api_id: 75remaypoe0ddp
  linkedin_api_secret: aRsYMhFYowHEEmFV

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  fb_api_id: <%= ENV["FB_API_ID"] %>
  fb_api_secret: <%= ENV["FB_API_SECRET"] %>
  fb_callback_url: <%= ENV["FB_CALLBACK_URL"] %>
  twitter_api_id: <%= ENV["TWITTER_API_ID"] %>
  twitter_api_secret: <%= ENV["TWITTER_API_SECRET"] %>
  gplus_api_id: <%= ENV["GPLUS_API_ID"] %>
  gplus_api_secret: <%= ENV["GPLUS_API_SECRET"] %>
  linkedin_api_id: <%= ENV["LI_API_ID"] %>
  linkedin_api_secret: <%= ENV["LI_API_SECRET"] %>

